language: node_js
node_js:
  - node

cache: npm

before_script:
  - npm install -g speccy

script:
- speccy lint --skip openapi-tags-alphabetical swiss-ng-api.yaml
- speccy lint --skip openapi-tags-alphabetical securities-orders.yaml
- speccy lint --skip openapi-tags-alphabetical foreign-exchange-single-legs.yaml
- speccy lint --skip openapi-tags-alphabetical foreign-exchange-swaps.yaml
