openapi: 3.0.1
info:
  title: Bankable Assets API Trading
  version: "tbd"
  x-logo:
    url: "https://openbankingproject-ch.github.io/obp-apis/swiss-ng-logo.png"
    backgroundColor: "#FFFFFF"
    altText: "Swiss OpenBankingProject Logo"
  description: |
    # Summary
    The **Bankable Assets API** ...

  license:
    name: Creative Commons Attribution 4.0 International Public License
    url: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Open Banking Project Switzerland
    url: https://www.openbankingproject.ch
    email: info@obp.ch

externalDocs:
  description: |
    Full Documentation
  url: https://github.com/openbankingproject-ch/obp-apis

servers:
  - url: https://api.dev.openbankingproject.ch
    description: Open Banking Project Switzerland Developer Portal
